import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import logo from "../assets/logo.svg"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Countries',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <main className='bg-gray-100 min-h-screen flex flex-col items-center'>
          <nav className='w-full flex items-center bg-white justify-center h-16'>
            <section className='container flex items-center gap-3'>
              <Image
                width={48}
                height={48}
                src={logo}
                alt='Ícone do globo terrestre'
              />
              <h1 className='font-bold text-2xl'>Lista de países</h1>
            </section>
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
